export const containers = {
  screenSearch: "min-h-screen flex flex-col items-center justify-center bg-slate-900 px-6 py-12 font-sans selection:bg-blue-500/30 overflow-y-auto",
  screenDashboard: "min-h-screen bg-slate-900 text-slate-100 p-6 md:p-10 font-sans selection:bg-blue-500/30 overflow-x-hidden",
  searchWrapper: "w-full max-w-4xl text-center space-y-8 mt-12",
  searchForm: "relative mt-8 max-w-3xl mx-auto",
  dashboardWrapper: "max-w-6xl mx-auto space-y-8 overflow-hidden",
  dashboardHeader: "flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-slate-800/50 p-6 rounded-2xl border border-slate-700/50 backdrop-blur-md shadow-lg",
  dashboardHeaderLeft: "flex items-center gap-5",
  dashboardHeaderRight: "flex gap-3",
  statGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6",
  mainGrid: "grid grid-cols-1 lg:grid-cols-3 gap-8 min-w-0",
  tableSection: "lg:col-span-2 bg-slate-800/50 rounded-2xl border border-slate-700/50 shadow-lg flex flex-col min-w-0 overflow-hidden",
  tableHeaderWrapper: "p-6 border-b border-slate-700/50 flex flex-col sm:flex-row sm:justify-between sm:items-center bg-slate-800/80 gap-4 min-w-0",
  tableTabsWrapper: "flex bg-slate-900/50 rounded-lg p-1 border border-slate-700/50",
  filtersGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4",
  filterCategoryCol: "flex flex-col",
  filterOptionsWrapper: "mt-2 p-3 bg-slate-800 border border-slate-700 rounded-lg shadow-lg flex flex-col gap-2 max-h-60 overflow-y-auto animate-in fade-in duration-200",
  flexCenter: "flex justify-center",
  flexRowCenter: "flex items-center",
  gap4: "gap-4",
  flexColumnStart: "flex flex-col items-start",
};
