export const texts = {
  h1Search: "text-4xl md:text-5xl font-bold tracking-tight text-white mb-4",
  h1Dashboard: "text-3xl font-bold tracking-tight text-white",
  h2Section: "text-xl font-semibold text-white mb-6 flex items-center gap-2",
  h2Table: "text-xl font-semibold text-white flex items-center gap-2",
  h3Filter: "text-white font-medium mb-4 flex items-center gap-2",
  subtitleSearch: "text-slate-400 text-lg",
  badgeStatus: "bg-emerald-500/10 text-emerald-400 px-2.5 py-0.5 rounded-full text-xs font-medium border border-emerald-500/20 flex items-center gap-1",
  badgeCategory: "text-sm",
  label: "text-sm font-medium text-slate-400 mb-1",
  valueLarge: "text-xl font-semibold text-slate-100",
  contactLabel: "text-sm text-slate-400 mb-0.5",
  contactValue: "text-slate-200 font-medium",
  contactValueLong: "text-slate-200 font-medium leading-relaxed",
  checkboxLabel: "text-sm text-slate-300 group-hover:text-slate-100 leading-tight",
  tableHeader: "p-4 font-medium",
  tableHeaderRight: "p-4 font-medium text-right",
  tableCellName: "font-medium text-slate-200",
  tableCellBadge: "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-700/50 text-slate-300 border border-slate-600/50",
  tableCellRightBlue: "p-4 text-right font-semibold text-blue-400",
  tableCellRightOrange: "p-4 text-right font-semibold text-orange-400",
  tableCellRightEmerald: "p-4 text-right font-semibold text-emerald-400",
  tableCellRightIndigo: "p-4 text-right font-semibold text-indigo-400",
};
